### ISSUE TITLE
Display proper message when app is opened on non-Chrome OS operating systems

### ISSUE THREAD

**Issue by dskaram** [GoogleChrome/chromeos_smart_card_connector#27]
1. Open connector on Windows/Mac/Linux Chrome.

Expected
Runs properly

Actual
?

We need to document the behavior on other platforms and show the proper signal to users. In the beginning we had blocked installation on other platforms but that got in the way of developers testing things out in their dev envrionments before publishing to the store (it's hard to develop on Chrome OS as middleware is a very low-level software that needs particular tools for development not found on Chrome OS).

**Comment by emaxx-google** [comment]
David, are you fine with this look?

![screenshot from 2016-08-25 15 45 08](https://cloud.githubusercontent.com/assets/17597418/17971403/043884f2-6adb-11e6-88c0-0675a243dbb4.png)
